Automation:
  display_name: restAssured_Automation
  git_clone_credentials_id: pipeline-ready-only
  use_https_clone: 'on'
  updateExistingJobs: "on"
  repositories:
    ^RestAssuredAutomation$:
      branches:
        ^main$:
          Regression_Batch1:
            jobType: pipeline
            filename: Jenkins/run_automated_test.Jenkinsfile
